export const ALL_MODULE_KEYS = [
  "calendar",
  "clients",
  "vehicles",
  "services",
  "appointments",
  "invoices",
  "payments",
  "inventory",
  "staff",
  "automations",
  "routePlanner",
  "vehicleInspection",
  "photoUploads",
  "vinDecoder",
  "insuranceWorkflow",
  "lapsedClients",
  "analytics",
  "quotes",
] as const;

export type ModuleKey = typeof ALL_MODULE_KEYS[number];

export const MODULE_RULES: Record<string, ModuleKey[]> = {
  auto_detailing: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
    "lapsedClients",
    "analytics",
  ],
  mobile_detailing: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "routePlanner",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
    "lapsedClients",
    "analytics",
  ],
  ppf_ceramic: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "photoUploads",
    "vinDecoder",
    "lapsedClients",
    "analytics",
  ],
  tint_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vinDecoder",
    "lapsedClients",
  ],
  mechanic: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vinDecoder",
    "vehicleInspection",
    "lapsedClients",
    "analytics",
  ],
  tire_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "vinDecoder",
    "analytics",
  ],
  car_wash: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "staff",
  ],
  body_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
    "insuranceWorkflow",
    "lapsedClients",
  ],
  wrap_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "photoUploads",
    "vinDecoder",
    "lapsedClients",
  ],
  dealership_service: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "vinDecoder",
    "insuranceWorkflow",
    "lapsedClients",
    "analytics",
  ],
  other_auto_service: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "quotes",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
    "lapsedClients",
    "analytics",
  ],
};

export const DEFAULT_MODULES: ModuleKey[] = [
  "calendar",
  "clients",
  "vehicles",
  "services",
  "appointments",
  "invoices",
  "payments",
  "inventory",
  "staff",
  "automations",
  "vehicleInspection",
  "photoUploads",
  "vinDecoder",
];

// Modules whose backend routes/tables are not implemented yet.
// We filter them out so the UI doesn't 404 during navigation.
const UNSUPPORTED_MODULES: ModuleKey[] = [
  "inventory",
  "automations",
  "lapsedClients",
  "vehicleInspection",
  "photoUploads",
];

export function getEnabledModules(businessType: string | null | undefined): Set<ModuleKey> {
  const modules = businessType && businessType in MODULE_RULES ? new Set<ModuleKey>(MODULE_RULES[businessType]) : new Set<ModuleKey>(DEFAULT_MODULES);
  for (const m of UNSUPPORTED_MODULES) modules.delete(m);
  return modules;
}

export function isModuleEnabled(modules: Set<ModuleKey>, module: ModuleKey): boolean {
  return modules.has(module);
}