export const ALL_MODULE_KEYS = [
  "calendar",
  "clients",
  "vehicles",
  "services",
  "appointments",
  "invoices",
  "payments",
  "inventory",
  "staff",
  "automations",
  "routePlanner",
  "vehicleInspection",
  "photoUploads",
  "vinDecoder",
] as const;

export type ModuleKey = typeof ALL_MODULE_KEYS[number];

export const MODULE_RULES: Record<string, ModuleKey[]> = {
  auto_detailing: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
  ],
  mobile_detailing: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "automations",
    "routePlanner",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
  ],
  ppf_ceramic: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "automations",
    "photoUploads",
    "vinDecoder",
  ],
  tint_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "vinDecoder",
  ],
  mechanic: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "vinDecoder",
    "vehicleInspection",
  ],
  tire_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "vinDecoder",
  ],
  car_wash: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "staff",
  ],
  wrap_shop: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "photoUploads",
    "vinDecoder",
  ],
  dealership_service: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "vinDecoder",
  ],
  other_auto_service: [
    "calendar",
    "clients",
    "vehicles",
    "services",
    "appointments",
    "invoices",
    "payments",
    "inventory",
    "staff",
    "automations",
    "vehicleInspection",
    "photoUploads",
    "vinDecoder",
  ],
};

export const DEFAULT_MODULES: ModuleKey[] = [
  "calendar",
  "clients",
  "vehicles",
  "services",
  "appointments",
  "invoices",
  "payments",
  "inventory",
  "staff",
  "automations",
  "vehicleInspection",
  "photoUploads",
  "vinDecoder",
];

export function getEnabledModules(businessType: string | null | undefined): Set<ModuleKey> {
  if (businessType && businessType in MODULE_RULES) {
    return new Set<ModuleKey>(MODULE_RULES[businessType]);
  }
  return new Set<ModuleKey>(DEFAULT_MODULES);
}

export function isModuleEnabled(modules: Set<ModuleKey>, module: ModuleKey): boolean {
  return modules.has(module);
}