import { permissionEnum, membershipRoleEnum } from "../db/schema.js";

export type MembershipRole = (typeof membershipRoleEnum.enumValues)[number];
export type PermissionKey = (typeof permissionEnum.enumValues)[number];

const ROLE_PERMISSIONS: Record<MembershipRole, PermissionKey[]> = {
  owner: [
    "dashboard.view",
    "customers.read",
    "customers.write",
    "vehicles.read",
    "vehicles.write",
    "services.read",
    "services.write",
    "quotes.read",
    "quotes.write",
    "appointments.read",
    "appointments.write",
    "jobs.read",
    "jobs.write",
    "invoices.read",
    "invoices.write",
    "payments.read",
    "payments.write",
    "team.read",
    "team.write",
    "settings.read",
    "settings.write",
  ],
  admin: [
    "dashboard.view",
    "customers.read",
    "customers.write",
    "vehicles.read",
    "vehicles.write",
    "services.read",
    "services.write",
    "quotes.read",
    "quotes.write",
    "appointments.read",
    "appointments.write",
    "jobs.read",
    "jobs.write",
    "invoices.read",
    "invoices.write",
    "payments.read",
    "payments.write",
    "team.read",
    "settings.read",
    "settings.write",
  ],
  manager: [
    "dashboard.view",
    "customers.read",
    "customers.write",
    "vehicles.read",
    "vehicles.write",
    "services.read",
    "services.write",
    "quotes.read",
    "quotes.write",
    "appointments.read",
    "appointments.write",
    "jobs.read",
    "jobs.write",
    "invoices.read",
    "invoices.write",
    "payments.read",
    "payments.write",
    "team.read",
    "team.write",
    "settings.read",
  ],
  service_advisor: [
    "dashboard.view",
    "customers.read",
    "customers.write",
    "vehicles.read",
    "vehicles.write",
    "services.read",
    "quotes.read",
    "quotes.write",
    "appointments.read",
    "appointments.write",
    "jobs.read",
    "jobs.write",
    "invoices.read",
    "invoices.write",
    "payments.read",
    "payments.write",
  ],
  technician: [
    "dashboard.view",
    "customers.read",
    "vehicles.read",
    "services.read",
    "appointments.read",
    "jobs.read",
    "jobs.write",
    "quotes.read",
    "invoices.read",
  ],
};

export function getDefaultPermissionsForRole(role: MembershipRole): Set<PermissionKey> {
  return new Set(ROLE_PERMISSIONS[role]);
}

export function roleHasPermission(role: MembershipRole, permission: PermissionKey): boolean {
  return getDefaultPermissionsForRole(role).has(permission);
}
